andreasgriffin/bitcoin-safe

- .github/workflows/build-appimage-test.yml
- .github/workflows/build-windows-test.yml
- tools/build-linux/appimage/Dockerfile
can the workflow be triggered manually?
> Added libxcb-cursor for Linux Mint

- .github/workflows/build-appimage-test.yml
- .github/workflows/build-windows-test.yml
there is a bug in guthub: https://github.com/orgs/community/discussions/25219
> Rename workflows (again)

- .vscode/launch.json
- bitcoin_safe/logging_handlers.py
- bitcoin_safe/logging_setup.py
- tests/non_gui/test_mail_handler.py
- open txt editor when critical error occurs
> Logging of Qt messages

- .github/workflows/build-mac-test.yml
- .github/workflows/python-tests.yml
- tools/build-mac/make_osx.sh
> Dmg build workflow change

- bitcoin_safe/dynamic_lib_load.py
- tools/build-wine/build_exe.sh
- tools/build-wine/prepare-wine.sh
- tools/build-wine/run_in_docker.sh
<div id='description'>
<h3>Summary by Bito</h3>
This pull request enhances the loading mechanism for the libzbar library on Windows by refactoring the ensure_pyzbar_works function and updating build scripts for better DLL management. Unnecessary lines were also removed to streamline the process.
<br>
<br>
<b>Unit tests added</b>: False
<br>
<br>
<b>Estimated effort to review (1-5, lower is better)</b>: 2
</div>
> Fix libzbar loading in Win

- bitcoin_safe/__init__.py
- bitcoin_safe/gui/qt/export_data.py
- poetry.lock
- pyproject.toml
- tools/build-mac/make_osx.sh
- also show alias of nostr chat
- update dependencies
> Fix mac build

- .github/PULL_REQUEST_TEMPLATE.md
- .github/workflows/build-and-test-mac.yml
<div id='description'>
<h3>Summary by Bito</h3>
This pull request adds a new checklist to the PR template to ensure all necessary steps are followed before merging. It also introduces a comprehensive GitHub Actions workflow for building and testing the application on MacOS, including environment setup, test execution, and DMG file validation.
<br>
<br>
<b>Unit tests added</b>: True
<br>
<br>
<b>Estimated effort to review (1-5, lower is better)</b>: 2
</div>
> Test in mac workflow

- .github/workflows/build-and-test-mac.yml
> workflow: screenshots

- .github/workflows/build-and-test-mac.yml
> Workflow: Fail is not running

- .github/workflows/build-and-test-mac.yml
> Workflow: try to uploadlogs

- .github/workflows/build-and-test-mac.yml
> Workflow: add other mac runner

- .github/workflows/build-and-test-mac.yml
> Workflow: Gatekeeper tests

- .github/workflows/build-and-test-mac.yml
> Workflow: try to capture output when failiure

- .github/workflows/build-and-test-mac.yml
> Workflow: enable matrix

- poetry.lock
- pyproject.toml
> Upgrade bitcoin-usb dependency

- bitcoin_safe/gui/qt/qt_wallet.py
- bitcoin_safe/storage.py
- added method `from_dump_downgrade_migration` for future downgrades
> Enable wallet downgrade (for future bdk1 upgrade)

- .github/PULL_REQUEST_TEMPLATE.md
- bitcoin_safe/gui/qt/qt_wallet.py
- bitcoin_safe/gui/qt/wallet_balance_chart.py
> Fix x axis range for empty chart

- README.md
- bitcoin_safe/__init__.py
- bitcoin_safe/__main__.py
- bitcoin_safe/dynamic_lib_load.py
- pyproject.toml
- tests/gui/qt/test_setup_wallet.py
- tools/build-mac/make_osx.sh
- tools/build-mac/osx.spec
- fixes ssl cert error  (that prevented updating the wallet block height)  by including certifi in datas in pyinstaller
- added Applications symlink in dmg
> Fix mac ssl error

- tools/build-mac/make_osx.sh
- tools/build-mac/osx.spec
> Remove underscore from Mac application name

- .github/workflows/build-and-test-mac.yml
> Fix workflow for dmg filename

- bitcoin_safe/__main__.py
- bitcoin_safe/dynamic_lib_load.py
- tools/build-wine/deterministic.spec
> Fix certifi  also for win

- README.md
- bitcoin_safe/__init__.py
- bitcoin_safe/descriptors.py
- bitcoin_safe/gui/qt/qr_components/quick_receive.py
- pyproject.toml
- sometimes additional address windows are opened.  This fixes this
> Fix ui bug of the quick receive

- bitcoin_safe/gnome_darkmode.py
> Dark mode tooltip background to black

- bitcoin_safe/gui/demo_wallets/SIGNET/demo-public-signet.wallet
- bitcoin_safe/gui/demo_wallets/TESTNET/demo-public-testnet.wallet
- bitcoin_safe/gui/demo_wallets/TESTNET4/demo-public-testnet4.wallet
- bitcoin_safe/gui/qt/sankey_bitcoin.py
- bitcoin_safe/gui/qt/ui_tx_viewer.py
- bitcoin_safe/signal_tracker.py
- bitcoin_safe/wallet.py
- tests/gui/qt/test_wallet_open.py
- replaces `search_index_tuple` with `is_my_address_with_peek`
- adds labels to the demo wallets
- proper signal disconnecting in SankeyBitcoin
- threaded AddressComparer.poisonous
> Speed-improvements, and SankeyBitcoin signal cleanup 

- bitcoin_safe/gui/qt/recipients.py
> Remove maxwidth from buttons, which causes issues in other languages

- bitcoin_safe/gui/qt/my_treeview.py
- bitcoin_safe/gui/qt/ui_tx/ui_tx_creator.py
- tests/gui/qt/helpers.py
- tests/gui/qt/test_setup_wallet.py
- tests/gui/qt/test_tx_signature_import.py
- tests/gui/qt/test_wallet_send.py
> Fix selection in qtreeview

- tools/build-linux/appimage/run_in_docker.sh
> Fix url for appimage

- README.md
> Add languages to readme

- tools/appimage_to_deb_converter.py
- tools/build-linux/appimage/run_in_docker.sh
- tools/build_tools_util.sh
> Apppimage and Deb reproducibility

- .github/workflows/build-appimage-and-test.yml
- .github/workflows/build-windows-and-test.yml
- .github/workflows/python-tests.yml
> Ensure libEGL is available in CI workflows

- .github/workflows/build-and-test-mac.yml
- .github/workflows/build-appimage-and-test.yml
- .github/workflows/build-windows-and-test.yml
> Workflow: Add option to skip build and just test release
